name: Build Solution Template

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    - name: Restore dependencies
      run: dotnet restore src/function

    - name: Build
      run: dotnet build src/function --no-restore

    - name: Test
      run: dotnet test src/function --no-build --verbosity normal

    - name: Publish solution code a folder called compiledFunction
      run: dotnet publish src/function -c Release -o compiledFunction

    - name: Copy scripts to the function folder
      run: cp -r scripts compiledFunction/scripts

    - name: Copy vm-extension templates to the function folder
      run: cp -r src/vmextension-template compiledFunction/templates

    - name: Zip the compiledFunction folder
      run: zip -r src/solution-template/function.zip compiledFunction

    - name: Create and upload solution-template zip file
      uses: actions/upload-artifact@v2.2.0
      with:
        # Artifact name
        name: solution-template
        # file, directory or wildcard pattern describing the content to upload
        path: src/solution-template
        if-no-files-found: error
        
